<?php

/**
 * Implements  hi_all_menu().
 */

function hi_all_menu()
{
  $items['hi_all'] = array( 
                            'title' => 'Begroeting',
                            'access arguments' => array('show_begroeting'),
                            'page callback' => 'hi_all_begroeting'
                          );

  return $items;
}

function hi_all_begroeting()
{
  $render= array( 
                  '#markup' => t('Hello Everybody')
                );

  return $render;
}

/**
 * Implements  hi_all_persmission().
 */

function hi_all_persmission()
{
  return array(
                'show_begroeting' => array(
                                            'title' => t('Toon begroeting'),
                                            'description' => t('Toelating om een begroeting getoond te krijgen.')
                                          )
              );
}